Add single json test to ci
perftool-incubator/crucible-ci pull request #66
Opened 2022-10-20 14:27 UTC by rafaelfolco

Exercise single json test case

2022-10-24 19:48 UTC, rafaelfolco commented
remember that you need to merge single-json.yaml into crucible-ci.yaml so that it becomes a proper dependency

2022-10-27 13:55 UTC, k-rister requested changes

2022-10-27 14:29 UTC, rafaelfolco commented on .github/workflows/crucible-ci.yaml
> +    - name: run crucible-ci->integration-tests
ack I can submit a separate one for controller build

2022-10-28 16:15 UTC, k-rister approved these changes

2022-10-31 16:48 UTC, merged